### ISSUE TITLE
(Protocols) Generate / Export valid RECS80 code fails

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#114]
Hi, i have an issue while trying to export/generate a  valid RECS80 code. See this pronto 

`0000 006D 0000 000C 0005 011B 0005 00BB 0005 011B 0005 00BB 0005 011B 0005 011B 0005 00BB 0005 00BB 0005 00BB 0005 011B 0005 011B 0005 0785`

It decodes correctly as

`protocol = RECS80, device = 5, obc = 35, misc = T=0 (131/5048/7573)`

However if i do this manually on the Generate Tab (Or export the code) it isnt accepted

F=35 outside of valid domain

Don't know if im doing something wrong, or if RECS80 is the wrong protocol for this case.. When you have some time please take a look . Thanks :)

**Comment by bengtmartensson** [comment]
Real bug, congrats! Get either the CI-build, or just IrpProtocols.ini.
