### ISSUE TITLE
irpmaster command to export lirc files

### ISSUE THREAD

**Issue by maghrab** [bengtmartensson/harctoolboxbundle#125]
Is there a command to export raw codes to a lirc file similar to irscrutinizer?

**Comment by bengtmartensson** [comment]
Short answer: no.

A better command line interface is planned, #26. Since the API is open, it should not be too hard to use that for achieving what you want to do.

**Comment by maghrab** [comment]
Thanks!

It seems that the hexadecimal code I am looking for comes from using --analyze flag, however, when I use it on raw codes it always outputs undetermined

**Comment by maghrab** [comment]
The hexadecimal code I am looking for comes from analyzeIR
An example would be:
AnalyzeIR: {38.0k,552,msb}<1,-1|1,-3>(16,-8,A:32,1,^112m,(16,-4,1,^110m)+){A=**0x20df40bf**}

When I capture a raw code, it always outputs undetermined

**Comment by bengtmartensson** [comment]
Then the raw code is possibly erroneous...my crystal ball is temporarily unavailable...

Have a look at the Arduino/IRremote export format, may be what you are looking for,

**Comment by maghrab** [comment]
Can you give me more information about that?

**Comment by bengtmartensson** [comment]
http://harctoolbox.org/IrScrutinizer.html#Arduino%2FInfrared4Arduino ?

**Comment by maghrab** [comment]
Thanks! Actually, I am looking for a command in terminal ( probably using irpmaster ) to get the hexadecimal keycode such as above. If you export using the lirc format, it will be in there.

**Comment by bengtmartensson** [comment]
Any more comments before closing?

**Comment by maghrab** [comment]
No, thanks a lot for your help! Great tool, Keep it up.
