### ISSUE TITLE
Generating raw codes from irpmaster

### ISSUE THREAD

**Issue by maghrab** [bengtmartensson/harctoolboxbundle#126]
Is there a command for irpmaster to generate a raw code given a string like :

protocol = NEC1, device = 2, obc = 30

It works on the generate tab on IrScrutinizer. Is there a command for that on irpmaster?

Thanks

**Comment by bengtmartensson** [comment]
$ irpmaster -p -r nec1 2 30
    Device Code: 2 Function: 30
    9024 -4512 564 -564 564 -1692 564 -564 564 -564 564 -564 564 -564 564 -564 564 -564 564 -1692 564 -564 564 -1692 564 -1692 564 -1692 564 -1692 564 -1692 564 -1692 564 -564 564 -1692 564 -1692 564 -1692 564 -1692 564 -564 564 -564 564 -564 564 -1692 564 -564 564 -564 564 -564 564 -564 564 -1692 564 -1692 564 -1692 564 -39756
    9024 -2256 564 -96156
    0000 006C 0022 0002 015B 00AD 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C

This is in the manual, see http://harctoolbox.org/IrpMaster.html#Usage+of+the+program+from+the+command+line

**Comment by maghrab** [comment]
Thanks!
