### ISSUE TITLE
Problem exporting multiple irplus files

### ISSUE THREAD

**Issue by HelenFoster** [bengtmartensson/harctoolboxbundle#139]
Hi, I can export one irplus file from IrScrutinizer. If I try to export more irplus files, it prints errors in the console and the exported file has 0 bytes. Restarting IrScrutinizer allows one more file to be exported. Using a build of 3d4129c .

```
ERROR:  'Variable 'encoding' is multiply defined in the same scope.'
FATAL ERROR:  'Variable 'creatingTool' is multiply defined in the same scope.'
Variable 'creatingTool' is multiply defined in the same scope.
File /tmp/exports/irplus_2016-07-30_11-22-19.irplus was successfully written.
```

**Comment by bengtmartensson** [comment]
Thanx for the bug report. Should work now.

**Comment by HelenFoster** [comment]
Thanks, it's working now.
