### ISSUE TITLE
Case of protocol names for LIRC export

### ISSUE THREAD

**Issue by HelenFoster** [bengtmartensson/harctoolboxbundle#142]
IrScrutinizer only exports a parametric LIRC file if the protocol is named "rc5" or "nec1" in lowercase, otherwise a raw LIRC file is created. Protocol names seem to be non-case-sensitive for most features (and it generates the raw codes using "RC5" to put into the raw LIRC file), so I guess that's a bug.

Currently, if I use Capture in the Parametric Remote table or import raw codes into it, the protocol appears in uppercase; but if I send the codes from the Generate tab, the protocol appears in lowercase.

**Comment by bengtmartensson** [comment]
Thanx for the bug report. Should work now.

**Comment by HelenFoster** [comment]
Thanks, it works.
