### ISSUE TITLE
IrScrutinizer immediately closes on OS X - El Capitan?

### ISSUE THREAD

**Issue by sofakng** [bengtmartensson/harctoolboxbundle#146]
I'm trying to run IrScrutinizer on OS X - El Capitan and when I launch it, I see the IrScrutinizer logo flash on the screen and then the application terminates.

I've tried running it from my desktop and also copying the app bundle to the Applications folder but it doesn't help.

I have Java v1.6.0 installed.

**Comment by bengtmartensson** [comment]
Java 1.6 is not supported. Please update,

**Comment by sofakng** [comment]
Sorry, I realized shortly after posting.  I've updated to 1.8 and it's working now.  Thanks!
