### ISSUE TITLE
Paste short cut (CTRL + v) not working on Windows on latest ci-build

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#171]
Hi, previously it was possible to use CTRL + V on scrutinze window. Has this been removed intentionally or is it a bug? Thanks

**Comment by bengtmartensson** [comment]
I can confirm that it is not working for me either.

It has neither been removed nor has it explicitly been put there, so I guess that something has happened with Swing/Java. Nevertheless, it makes sense to have it working. 

Workarounds: Right Mouse -> paste or Edit -> Paste signal does it. If you are using X Windows, you can also paste the "selection" with the middle mouse button.

**Comment by bengtmartensson** [comment]
Appears to have gone wrong with f2f57773833738bb4dbc228f0818f1ef2e8f6c6b, (fixing #127), added file dropping support, inadvertently breaking pasting support.

**Comment by bengtmartensson** [comment]
@irplus-remote : The problem is believed to be fixed. Please check and reopen if appropriate.

Again, many thanx for reporting.

**Comment by irplus-remote** [comment]
Thanks, for some reason i can't get the ci-build though. Maybe a temporary issue, will retry later

https://github.com/bengtmartensson/harctoolboxbundle/releases/download/ci-build/IrScrutinizer-bin.zip

**Comment by bengtmartensson** [comment]
There has been some issues with travis and/or the Github API. (At least) At this moment, the CI build should be OK though.

**Comment by irplus-remote** [comment]
Hi, i've tested and it works partly now. :) However there seems to be a small weakness.

If i use CTRL + A to select all, and CTRL + V to paste a new code, the old input is kept and only attached to it, instead of being deleted (as it would be done usually)

**Comment by bengtmartensson** [comment]
Sigh... I "knew" it was not right to reimplement the pasting logic :-\

Thanx for the feedback.

**Comment by irplus-remote** [comment]
Also CTRL + C doesnt work :/   (Copy selection)

**Comment by bengtmartensson** [comment]
Please try the current CI-build.

**Comment by bengtmartensson** [comment]
OK to close?

**Comment by irplus-remote** [comment]
I guess so, seems to be ok now

**Comment by bengtmartensson** [comment]
Ok, nice to hear that.

Thank you for this (and other!) bug reports; helping to make IrScrutinizer better.
