### ISSUE TITLE
Open last file does not work anymore 

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#193]
Hi, i can't use the "Open last file" button anylonger. Any idea?

Error : No application is associated

-> But it is

Maybe related to this? https://github.com/bengtmartensson/harctoolboxbundle/issues/149

**Comment by bengtmartensson** [comment]
It is the operating system (which one are you using?) that associates applications and that produces that error message. Which type is failing? Also Java's Desktop can be involved, which Java are you using?

> Maybe related to this? #149

That is with girr only, which are now copied to .txt.

**Comment by irplus-remote** [comment]
I'm using Windows, and the files are associated with Notepad++ (any type fails including lirc). Also it worked before. Happening since i am using the latest build. (Java is oracle JDK on windows)

I will now update Notepad++ and Java just to be sure though

**Comment by bengtmartensson** [comment]
Please try the CI-build.

**Comment by irplus-remote** [comment]
Working again :)

**Comment by bengtmartensson** [comment]
Great! Thanx for the bug report.
