### ISSUE TITLE
Unsupported IrToy protocol version

### ISSUE THREAD

**Issue by Amelichev** [bengtmartensson/harctoolboxbundle#195]
I have IrToy V212. Is it supported? I can capture signal with this IrToy. But can not transmit - when I try to transmit I always see this mistake "Unsupported IrToy protocol version"

**Comment by bengtmartensson** [comment]
That firmware version is not supported, although capture happens to work. The good news is that (as opposed to the IrDroid) the firmware can be easily updated over USB. You will find the firmware and instructions and the firmware at the dangerous prototypes site. Use the 2.2 version.

**Comment by Amelichev** [comment]
Thanks! I've sucsessfully upraded IRTOY to ver 2.2 and Transmittion is working.

**Comment by bengtmartensson** [comment]
Happy to hear that!!

**Comment by bengtmartensson** [comment]
Cf. #176, adding support for 2.0 and 2.1.
