### ISSUE TITLE
Can I generate protocol GAP-1546-3866-16?

### ISSUE THREAD

**Issue by Amelichev** [bengtmartensson/harctoolboxbundle#196]
DecodeIR: GAP-1564-3866-16 DEV=106 OBC=39 misc=6A.27

**Comment by Amelichev** [comment]
this is MENU button

**Comment by Amelichev** [comment]
![1111](https://cloud.githubusercontent.com/assets/25001954/24542991/6fe22d6c-1606-11e7-84c0-99ce02c3b9a2.jpg)

**Comment by Amelichev** [comment]
Can I generate signal of other buttons?

**Comment by bengtmartensson** [comment]
"GAP-***" is not a protocol, is rather a form of error message from DecodeIR (no know protocol matched).

You can always use the  raw form of the signals.

**Comment by Amelichev** [comment]
Thanks! I've tryed once more, and I see that it is SIM2 protocol. I have always genereted all codes from this table.

**Comment by bengtmartensson** [comment]
Glad that it works!
