### ISSUE TITLE
Send IR Code with Parameters

### ISSUE THREAD

**Issue by nitulkukadia** [bengtmartensson/harctoolboxbundle#199]
I want to add parameter values to IR code. 
I get below information for Samsung on http://irdb.tk/find/ (Find IR codes) 
**Below is protocol information:** Protocol Samsung20, device 1, subdevice 8, OBC 50 

**Temp+ Pronto Hex:** 0000 006C 0000 0016 00AD 00AD 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0955 

Now, to increase Temperature from 20 to 21. 
Where should I place 21 in this pronto code while sending to Samsung AC. 
Or 
I should not bother about Temperature values and it is just increase in volume code and temperature value will be handled by AC itself. 
Also, 
Does above parameter based code are exist for other devices. 
Or 
No devices uses parameter based codes.

**Comment by bengtmartensson** [comment]
Not an issue for or with the present program.
