### ISSUE TITLE
so-files in git tree

### ISSUE THREAD

**Issue by leamas** [bengtmartensson/harctoolboxbundle#2]
So-files (pre-compiled sources) is normally not considered as git artifacts - a git tree is about sources. Could you please consider removing these files and instead add them when creating a release e. g. as described in https://github.com/blog/1547-release-your-software?

**Comment by bengtmartensson** [comment]
Disagree. "Normally" indicates a rule with exceptions. These files are:
- Not expected to change "very often", or more likely, not at all,
- At least for some, I cannot create them (Windows compiles) (from that point of view, they are "sources")

If I "had" to remove them, I would have to store these artifacts in another version control system, defeating the purpose of Github.

That said, the README could stand some improvement :-).

**Comment by leamas** [comment]
Well, you certainly don't have to remove them , it's your repo. 

That said, a possible middle ground could be to let them be there for now, but  re-evaluate the situation after the first release (in which case they are available in the release tarballs).

BTW, you should perhaps mark for which arm architecture the LInux-arm file is for (32bit v5?).

I have a README update at hand, but will send a merge request before going into that.

**Comment by bengtmartensson** [comment]
The ARM file was nuked (old anyhow). Looking forward for your README.

**Comment by leamas** [comment]
Which heavily depends on last merge request, which to a large extent is about building the libs.
