### ISSUE TITLE
(Hardware) Replace RXTX

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/harctoolboxbundle#20]
RXTX is a never ending source of problems, both in porting, installation, and reliability. It is essentially very old code, that appears never to have been finished. 

There are alternatives on the Internet. First, Arduino IDE should be inspected; they migrated away from RXTX recently; is there anything there to "steal"?

**Comment by bengtmartensson** [comment]
Some alternatives: JSSC, nrjavaserial (Openremote migrated RXTX-> nrjavaserial)

**Comment by HelenFoster** [comment]
Arduino migrated to JSSC, and seem to be having much less trouble with serial. JSSC is also packaged in Fedora and Debian. Looks like no-one is maintaining it though.
https://github.com/scream3r/java-simple-serial-connector
https://github.com/arduino/Arduino/commit/f334e67
https://github.com/arduino/Arduino/commit/48c1223

**Comment by bengtmartensson** [comment]
Thank you for the comment.

The main difference is, I think, that JCCS does not do any locking of the device file at all. (So therefore there are less problems?). Does device locking still make sense, or is it an artifact from the VAX  age? nrjavaserial still have [issues](https://github.com/NeuronRobotics/nrjavaserial/issues/60).

**Comment by HelenFoster** [comment]
Not doing any locking makes the serial access more portable and avoids a large proportion of the problems.

It appears that Arduino with JSSC bypasses serial port locks placed by other applications. Since it is very popular software, this makes such locks ineffective in general, so the Arduino team have basically decided for the world that serial port locking is dead.

**Comment by HelenFoster** [comment]
Testing in Windows 10, only one application can connect to the serial port, whether the applications are using RXTX, JSSC or a mixture. Probably the locking is done by the OS, though I haven't found any page stating this explicitly.

**Comment by bengtmartensson** [comment]
Replaced by https://github.com/bengtmartensson/HarcHardwareBundle/issues/1. in the vein of #215.
