### ISSUE TITLE
Manufacturers not shown in IrScrutinizer 1.4

### ISSUE THREAD

**Issue by nitulkukadia** [bengtmartensson/harctoolboxbundle#200]
I have installed IrScrutinizer 1.4 in windows machine.

It does not show any manufacturers when we click in selection menu to select it, in IRDB tab.
IrmMaster version 1.4
Decode IR version 2.45
Java : 1.8
Windows 7 x86

**Comment by bengtmartensson** [comment]
Did you select "Select me to load"?

If so, turn on Options -> Verbose, restart, and post a screen shot.

**Comment by nitulkukadia** [comment]
I got manufacturers. 
I didn't clicked on "Select me to load".
