### ISSUE TITLE
Add support for RC6-6-28 Protocol

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#209]
Hi, new HD Sky boxes seem to use a protocol which is not properly supported by irscrutinizer:

It renderes the wave correctly in the scrutinize tab, but it is not possible to generate codes with it or use the "scrutinize remote" tab  as it says unknown protocol

I hope this is ok posting it into the issues 

```
0000 006D 001D 0000 005B 0023 000F 000F 000B 0013 000F 001C 000F 001C 0023 000F 000B 0013 000F 000F 000F 0013 000F 000F 000F 0013 0013 000B 000B 0013 001C 0023 000F 000F 000F 000F 000F 000F 000F 0013 000F 000F 001C 000F 000F 0023 001C 0023 000F 000F 001C 0023 0023 000F 000F 0023 000F 000F 000F 0013 000F 0001
```

**Comment by bengtmartensson** [comment]
Thank you for the ticket; should be fixed.
