### ISSUE TITLE
XCF file import should support version XCF version 5.

### ISSUE THREAD

**Issue by Amelichev** [bengtmartensson/harctoolboxbundle#219]
Hello! Can you help me with Pronto XCF file? 
http://files.remotecentral.com/view/2447-4550-1/nakamichi_soundspace_10_receiver.html
can't open it with irscrutinizer: "passeexception on line - 1: No Modules element present"
May be you can fix this problem?

**Comment by bengtmartensson** [comment]
@Amelichev : Thank you very much for reporting this. The background is that there are (at least) two different version of the xcf format, and the version 5 was never implemented. Stay tuned.

**Comment by bengtmartensson** [comment]
Please try the [CI-build](https://github.com/bengtmartensson/harctoolboxbundle/releases/tag/ci-build).

**Comment by Amelichev** [comment]
Thanks! Yes, this version can open XCF ver 5!

**Comment by Amelichev** [comment]
Thanks! Yes, this version can open XCF ver 5!

**Comment by bengtmartensson** [comment]
Thank you for reporting it. Actually, I knew about the problem since the XCF importer was originally written, but never cared to implement version 5 until someone needed it.
