### ISSUE TITLE
16-bit NEC Yamaha Protocol Generation

### ISSUE THREAD

**Issue by Amelichev** [bengtmartensson/harctoolboxbundle#220]
Hi! Can't find 16bit NEC Protocol Generation, or it works not correct. For example this codes:
![image001](https://user-images.githubusercontent.com/25001954/28860645-168f070a-7766-11e7-96fe-70b95bd106d5.png)
Key name "RED" (ID1, ZONE A) = 7A-C0BF
I choose NEC1-f16 Protocol, and try to generati it, byt the generated signal=7A-BEC1
Then I found this page: http://www.awe-europe.com/documents/Control%20Docs/irhex_converter.html
And I had to convert hex to pronto to generate right signal.

May be I'm doing sth wrong?

**Comment by bengtmartensson** [comment]
Probably you are interpreting the parameters in the table wrong. It is not very clear... See the screenshot for the parameters to select for "RED". Note that hexadecimal values has to be prefixed by "0x".

![screenshot from 2017-08-02 10-13-30](https://user-images.githubusercontent.com/11508922/28863993-59698df2-776b-11e7-862e-77ad9d883cd8.png)

**Comment by Amelichev** [comment]
Ок, I genetate 0x7A 0xC0BF:
![wrong](https://user-images.githubusercontent.com/25001954/28866730-851c9f82-777c-11e7-8e8f-3b0b929091d4.jpg)
But the right signal must be:
![right](https://user-images.githubusercontent.com/25001954/28866754-95c53a24-777c-11e7-9445-ea588d991ed9.jpg)

When I capture signal from original remote I see decode IR:
![decode](https://user-images.githubusercontent.com/25001954/28867035-769a80d6-777d-11e7-97aa-f8d8718ce99c.jpg)

**Comment by bengtmartensson** [comment]
I did not say it explicitly, but exactly what the table means you have to ask its creator. It is by no means clear. 

There are a few [different interpretations in DecodeIR of the parameters in the NEC protocol](http://www.hifi-remote.com/wiki/index.php?title=DecodeIR#Variant_IRstreams_in_NEC_protocols), but this is not synced with the rendering in IrScrutinizer. This will change with the migration to IrpTransmogrifier, cf. #212.

This is not an IrScrutinizer issue.
