### ISSUE TITLE
No EXE of IrScrutinizer on Windows

### ISSUE THREAD

**Issue by m-usmankhan** [bengtmartensson/harctoolboxbundle#224]
When I install IrScrutinizer in windows, it installs fine. But when I launch it, it opens the zip file. And I cant find any executable. Am i doing it right?

**Comment by bengtmartensson** [comment]
Have you installed Java correctly? If so, try [this](http://www.harctoolbox.org/IrScrutinizer.html#%28Windows%29+When+I+double+click+on+the+IrScrutinizer+symbol%2C%0Ainstead+of+the+program+starting%2C+WinRar+%28or+some+other+program%29+comes%0Aup.).

**Comment by m-usmankhan** [comment]
Yes. I got the problem fixed. Actually JAR was associated with Winrar. I removed it.
