### ISSUE TITLE
IrScrutinizer - Broadlink Python -ir  error

### ISSUE THREAD

**Issue by markfal** [bengtmartensson/harctoolboxbundle#230]
Hello there, I have  question to ask if I may with regards to exporting via Broadlink Python –ir

When I do and run the exported script  I get the error below .. Cant work out what I’m doing wrong. Any assistance is much appreciated

Regards

Mark

python broadtest.py 
  File "broadtest.py", line 21
    ],
    ^
SyntaxError: invalid syntax

PY script

cat broadtest.py
#! /usr/bin/env python

# This file has been automatically generated by IrScrutinizer.

# For problems, bugs, and suggestions, please open an issue at
# https://github.com/bengtmartensson/harctoolboxbundle/issues

import argparse
import broadlink

IR_TOKEN = 0x26
RF_433_TOKEN = 0xB2
RF_315_TOKEN = 0xD7

commands = {
    # Command #1: On + SAT;     'On + SAT': [
        IR_TOKEN,
        bytearray(),
        bytearray.fromhex('1E5B1E1E1E1E1E3D1E1E1E1E1E1E1E1E1E1E1E1E1E3D1E3D1E3D1E3D1E3D1E3D1E3D1E3D1E3D1E3D1E3D1E1E1E1E1E1E1E1E1E3D1E1E1E3D1E1E1E3D1E3D1E3D1E3D1E1E1E1E1E3D1E0001CD'),
        bytearray()
    ],
}

def get_command_data(command_name, count):
    cmd = commands[command_name]
    buffer = bytearray()
    buffer.append(cmd[0])
    repeat_only = len(cmd[1]) == 0 and len(cmd[3]) == 0
    buffer.append(count - 1 if repeat_only else 0)
    seq = cmd[2] if repeat_only else mk_sequence(cmd, count)
    buffer.append(len(seq) % 256)
    buffer.append(len(seq) / 256)
    return buffer + seq

def mk_sequence(cmd, count):
    no_repeats = count if len(cmd[1]) == 0 else count - 1
    data = cmd[1]
    for i in range(0, no_repeats):
        data = data + cmd[2]
    return data + cmd[3]

def auto_int(x):
    return int(x, 0)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(fromfile_prefix_chars='@')
    parser.add_argument("--device", help="device definition as 'type host mac'")
    parser.add_argument("--type", type=auto_int, default=0x2712, help="type of device")
    parser.add_argument("--host", help="host address")
    parser.add_argument("--mac", help="mac address (hex reverse), as used by python-broadlink library")
    parser.add_argument("--count", default=1, type=int, help="Number of times to send signal")
    parser.add_argument("command", help="Name of command to send, as defined in the code")
    args = parser.parse_args()

    if args.device:
        values = args.device.split()
        type = int(values[0], 0)
        host = values[1]
        mac = bytearray.fromhex(values[2])
    else:
        type = args.type
        host = args.host
        mac = bytearray.fromhex(args.mac)

    dev = broadlink.gendevice(type, (host, 80), mac)
    dev.auth()
    payload = get_command_data(args.command, args.count)
    dev.send_data(payload)

**Comment by bengtmartensson** [comment]
Why was this closed? Somehow invalid Python was generated (there is a missing line feed), this is a bug, and should be addressed.

How exactly did you generate that file?; please describe.

**Comment by markfal** [comment]
Hi there i closed because  i worked around it
Cheers
Nark


Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network
-------- Original message --------From: Bengt Martensson <notifications@github.com> Date: 13/4/18  4:45 pm  (GMT+10:00) To: bengtmartensson/harctoolboxbundle <harctoolboxbundle@noreply.github.com> Cc: markfal <mark.falzon5@bigpond.com>, State change <state_change@noreply.github.com> Subject: Re: [bengtmartensson/harctoolboxbundle] IrScrutinizer - Broadlink
  Python -ir error (#230) 
Why was this closed? Somehow invalid Python was generated (there is a missing line feed), this is a bug, and should be addressed.
How exactly did you generate that file?; please describe.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bengtmartensson/harctoolboxbundle","title":"bengtmartensson/harctoolboxbundle","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bengtmartensson/harctoolboxbundle"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bengtmartensson in #230: Why was this closed? Somehow invalid Python was generated (there is a missing line feed), this is a bug, and should be addressed.\r\n\r\nHow exactly did you generate that file?; please describe."}],"action":{"name":"View Issue","url":"https://github.com/bengtmartensson/harctoolboxbundle/issues/230#issuecomment-381040115"}}}

**Comment by bengtmartensson** [comment]
I found the problem and have checked in a fix.

Thanx for bringing this problem to my attention, thus helping making IrScrutinizer better.

**Comment by markfal** [comment]
Fantastic  ... 





Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network
-------- Original message --------From: Bengt Martensson <notifications@github.com> Date: 13/4/18  5:57 pm  (GMT+10:00) To: bengtmartensson/harctoolboxbundle <harctoolboxbundle@noreply.github.com> Cc: markfal <mark.falzon5@bigpond.com>, State change <state_change@noreply.github.com> Subject: Re: [bengtmartensson/harctoolboxbundle] IrScrutinizer - Broadlink
  Python -ir error (#230) 
I found the problem and have checked in a fix.
Thanx for bringing this problem to my attention, thus helping making IrScrutinizer better.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bengtmartensson/harctoolboxbundle","title":"bengtmartensson/harctoolboxbundle","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bengtmartensson/harctoolboxbundle"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bengtmartensson in #230: I found the problem and have checked in a fix.\r\n\r\nThanx for bringing this problem to my attention, thus helping making IrScrutinizer better."}],"action":{"name":"View Issue","url":"https://github.com/bengtmartensson/harctoolboxbundle/issues/230#issuecomment-381055977"}}}
