### ISSUE TITLE
Why again an error?

### ISSUE THREAD

**Issue by bakdamir** [bengtmartensson/harctoolboxbundle#237]
![2018-06-08 08-12-29](https://user-images.githubusercontent.com/10049744/41138659-e23daa7e-6af3-11e8-893b-766fa0bc205d.png)

**Comment by bakdamir** [comment]
Protocol NEC not known?

**Comment by bengtmartensson** [comment]
Yes, the current version does not know "NEC"  [background](http://www.hifi-remote.com/wiki/index.php?title=DecodeIR#NEC) You can manually change to for example "NEC1".

Please check the [current snapshot version}(https://github.com/bengtmartensson/harctoolboxbundle/releases/tag/ci-build).

**Comment by bakdamir** [comment]
![2018-06-08 22-49-32](https://user-images.githubusercontent.com/10049744/41175595-a0747dfe-6b6e-11e8-938b-4fa4c0940cee.png)

**Comment by bakdamir** [comment]
does not start

**Comment by bengtmartensson** [comment]
Please address ONE thing per issue, and use *sensible* titles.

The missing file should be fixed in a recent commit.

**Comment by bengtmartensson** [comment]
@bakdamir : please confirm that the problem with the missing file was fixed in the recent snapshot.

**Comment by bakdamir** [comment]
Yes, corrected! I checked it now, thank you.
