### ISSUE TITLE
Delete selected does not work properly (V. 1.4.2)

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#253]
Hi, found a bug..
It deletes the wrong rows unfortunately.

![image](https://user-images.githubusercontent.com/14196521/45374982-01b3ac00-b5f4-11e8-8226-9d0a390cac3d.png)

![image](https://user-images.githubusercontent.com/14196521/45374983-01b3ac00-b5f4-11e8-9312-a2bff42e3063.png)

**Comment by bengtmartensson** [comment]
Thank you very much for this bug report.

I can confirm it: To reproduce: create three lines, select 1 and 3. "Delete selected" will delete 1 and 2. However, I cannot make sense of your stack trace.

**Comment by irplus-remote** [comment]
Oh don't worry the stacktrace is from a wrong capture nothing to do with the issue.

And also the "DELETE" key does not work as a shortcut ^^

**Comment by bengtmartensson** [comment]
Try the current snapshot; this should fix it.

> And also the "DELETE" key does not work as a shortcut ^^

I claim it does, although it may not be they way you expect it to. The menu has to be visible. This is not to say that the behavior is perfect...

**Comment by bengtmartensson** [comment]
@irplus-remote 
Please confirm that the original problem was solved.

**Comment by irplus-remote** [comment]
Issue solved ;) (what is strange though is that each code is read with the previous code.  E.g i press on rremote :   1,2,2       , irscrutinizer will capture :  1,1,2  (need to figure out, but it has nothing to do with this one)

**Comment by bengtmartensson** [comment]
Glad that it is fixed.

> each code is read with the previous code. E.g i press on rremote : 1,2,2 , irscrutinizer will capture : 1,1,2 (need to figure out, but it has nothing to do with this one)

Sorry, I can't do anything with a description like that. Can be a driver or hardware problem.
