### ISSUE TITLE
Capturing raw remote -> NPE

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#255]
Happens when starting to Capture in "Raw Remote" Mode
![image](https://user-images.githubusercontent.com/14196521/45498504-70227680-b77a-11e8-82dc-18046b2df5a4.png)

But "Parametric Remote" works and starts reading.

Exc seems to be similar to this one we had earlier: https://github.com/bengtmartensson/harctoolboxbundle/issues/241

**Comment by bengtmartensson** [comment]
Blush... that is embarrassing...  Thanx a ton for finding this.

Should be fixed in the latest commit and snapshot.

**Comment by irplus-remote** [comment]
fixed
