### ISSUE TITLE
IrScrutinizer wav file read problem

### ISSUE THREAD

**Issue by Pavlex4** [bengtmartensson/harctoolboxbundle#262]
I connected 2 ir leds to audio jack and I plugged it in microphone port of pc. After recording ir signal with audacity and exporting it as wav pronto code wasn't displayed in IrScrutinizer
wav file: https://www.sendspace.com/file/17caqg

**Comment by bengtmartensson** [comment]
I can confirm that IrScrutinizer 1.4.2 does reject the file. The experimental branch `IrpTransmogtifier` does however accept it, but it looks ... weird. 

It is not on my list of priorities to tweak the wave importer.  I will however likely accept contributed fixes.
