### ISSUE TITLE
Bundle minimal JRE also for Windows and Mac

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/harctoolboxbundle#283]
Guided by the success of #279 (thanx @probonopd), it is natural to raise the question in the title.

For Windows, Inno installer can optionally install a bundled JDK as install option.

For Mac, installing Java is a bit more complicated than on Linux/Windows.

However, the "generic binary distribution" should come without Java, to stay "generic binary".

As comparision, Arduino (IDE) already comes with bundled JDK.

**Comment by probonopd** [comment]
Thank you. Can the AppImage with JRE be downloaded somewhere?

**Comment by bengtmartensson** [comment]
CI & Travis are enabled again. But please note that this is an early pre-release of Version 2, "powered by IrpTransmogrifier".

**Comment by probonopd** [comment]
Thank you. Runs well for me!

![](https://user-images.githubusercontent.com/2480569/59881134-4861de00-939e-11e9-93ff-a4ed55cc49cc.png)
