### ISSUE TITLE
Support command  line program IrpTransmogrifier in AppImage

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/harctoolboxbundle#285]
The "package" comes with the GUI program IrScrutinizer and the command line program [IrpTransmogrifier](https://github.com/bengtmartensson/IrpTransmogrifier). Both are installed (made available as commands) with Windows and the generic binary distribution. Leaves AppImage and the Mac app, which presently only offers the GUI. I do not care right now for the Mac...

@probonopd , comments?

**Comment by probonopd** [comment]
You can put it into the AppImage and then use something along those lines:

https://gitlab.com/inkscape/inkscape/blob/master/packaging/appimage/AppRun#L8-29

**Comment by bengtmartensson** [comment]
Should work now.

(Preliminary) documentation:

If the AppImage is invoked with basename `irptransmogrifier` (note: all lowercase), instead the command line program IrpTransmogrifier will be invoked on the arguments. Alternatively, if the AppImage is invoked with the first argument (exactly) equal to `irptransmogrifier`, that program will be invoked on the remaining arguments.

@probonopd : Thanx for your support!
