### ISSUE TITLE
IrScrutinizer-2.0.0-8bf4199-SNAPSHOT.exe capture and export errors

### ISSUE THREAD

**Issue by DanielTheGreat** [bengtmartensson/harctoolboxbundle#290]
**Issue 1:**
Start IrScrutinizer
Open GirsLite device
Scrutinize remote tab
Parametric Remote
Add capture name (e.g. 'Test')
Capture
Fire some IR commands (from JVC RM-SRX8032R) at the Nano device's sensor
Error (in console pane) on each capture: "Undecodable signal, ignored" (these same signals were decoded by v1.4.3)
Capture (off)

**Issue 2:** (continuing from above settings, changed as below)
Raw Remote
Capture
Fire some IR commands (from JVC RM-SRX8032R) at the Nano device's sensor
Capture (off)
Enter command names in Name column
Export tab
Export dir. (default): C:\Users\Daniel\AppData\Local\Temp\\exports (note double-backslash!)
Format: Arduino/Infrared4Arduino
Girr export tab
Stylesheet (default): simplehtml.xsl
Export raw remote
Error pop-up: "C:\Users\Daniel\AppData\Local\Temp\exports\arduino\infrared4arduino_2019-07-13_16-44-49.ini (The system cannot find the path..."
![Export_file_error](https://user-images.githubusercontent.com/17305139/61168190-bbb9d280-a58d-11e9-9c22-462ef1ffc7c0.png)

**Comment by bengtmartensson** [comment]
Please open one issue per ... issue.

1. How do you envision that I should analyze this? Please post the non-decoding signals, preferably in a new issue.

2. Thank you very much for this. Turned out that it was dependent on the "/" in the format name; the problem occurred only on Windows. Should work in the most current snapshot. Please verify.

**Comment by bengtmartensson** [comment]
You have made a separate issue for issue 1, and there report the export as working. So I am closing this as fixed.
