### ISSUE TITLE
IrScrutinizer-2.1.0.exe "Please install java before you install IrScrutinizer"

### ISSUE THREAD

**Issue by pico563** [bengtmartensson/harctoolboxbundle#320]
IrScrutinizer-2.1.0.exe  refuse to install
giving this message
**_"Please install java before you install IrScrutinizer"_**
 ---

1. java Version 8 update 221 (build 1.8.0_221-b11) already installed.
2. 
![IrScrutinizer](https://user-images.githubusercontent.com/24532917/64092022-45e31380-cd53-11e9-8ead-c64a118056ee.png)

**Comment by pico563** [comment]
what Java type and version should I install ?
thanks

**Comment by bengtmartensson** [comment]
Thank you very much for the bug report. Sorry for that, the algorithm for detecting the existence of Java must have went wrong.

For a quick solution use [this new setup.exe](https://github.com/bengtmartensson/harctoolboxbundle/releases/download/Version-2.1.0/IrScrutinizer-2.1.0-no-javacheck.exe).

The long time solution is probably #283, not another half-working Java detection algorithm.

Again, thank you very much for the bug report.

**Comment by pico563** [comment]
thank you for your good work.
