### ISSUE TITLE
Undecodable signal, ignored

### ISSUE THREAD

**Issue by bakdamir** [bengtmartensson/harctoolboxbundle#326]
LocalSerialPortBuffered.readString: received "f=38461 +4466 -4507 +562 -564 +560 -1689 +562 -1691 +560 -1694 +560 -565 +560 -565 +560 -566 +560 -566 +562 -561 +562 -1689 +562 -1691 +560 -1693 +560 -565 +560 -565 +560 -565 +560 -580 +562 -563 +562 -561 +562 -1691 +560 -1693 +562 -565 +560 -565 +560 -565 +560 -563 +560 -1689 +562 -1694 +560 -565 +560 -563 +560 -1691 +560 -1691 +560 -1689 +562 -1693 +562 -46198 +4469 -4502 +560 -1687 +560 -65535 +4469 -4504 +560 -1687 +562 -65535 +4469 -4502 +560 -1687 +560 -65535 +4469 -4501 +562 -1685 +562 -65535 +4469 -4502 +560 -1685 +562 -65535 +4469 -4501 +560 -1687 +562 -65535 +4468 -4501 +562 -1687 +560 -65535 +4469 -4502 +560 -1687 +562 -65535 +4467 -4502 +562 -1685 +562 -65535"
Undecodable signal, ignored

**Comment by bengtmartensson** [comment]
Please tell us in detail  what you are trying to do, what version you are using, hardware used, and what you expect.

**Comment by bakdamir** [comment]
Trying to read the remote.
![Снимок экрана от 2019-06-19 07-38-00](https://user-images.githubusercontent.com/10049744/66953776-29cfd300-f070-11e9-938a-52da9c67206f.png)

**Comment by bakdamir** [comment]
![image](https://user-images.githubusercontent.com/10049744/66954779-1a518980-f072-11e9-8d10-2f3ae100e422.png)

**Comment by bakdamir** [comment]
trying to read the remote

**Comment by bengtmartensson** [comment]
Does it help selecting  OPtions -> Invoke repeat finder, Options -> Invoke signal cleaner?

**Comment by bakdamir** [comment]
Helps with scrutinize signal,at scrutinixe remote without changes

**Comment by bengtmartensson** [comment]
Good news: I have been able to reproduce!

**Comment by bengtmartensson** [comment]
Turned out that it was much more "interesting" than I thought. Thank you very much for the report!!

Please try: https://github.com/bengtmartensson/harctoolboxbundle/releases/tag/ci-build; it should fix the problem.

I would like you to test both with and without "Invoke repeatfinder" enabled.

**Comment by bakdamir** [comment]
Thank you. I will definitely test and let you know.

**Comment by bakdamir** [comment]
Invoke repeat finder enabled
![image](https://user-images.githubusercontent.com/10049744/67051438-1c881680-f14c-11e9-8fbc-32a2c8ab893c.png)
Invoke repeat finder disabled
![image](https://user-images.githubusercontent.com/10049744/67051572-843e6180-f14c-11e9-86f4-8e0cb1a0640e.png)

**Comment by bengtmartensson** [comment]
That looks quite good. Can we consider this fixed and close the issue?

**Comment by bakdamir** [comment]
Yes.
