### ISSUE TITLE
Undecodable signal, ignored

### ISSUE THREAD

**Issue by bakdamir** [bengtmartensson/harctoolboxbundle#333]
Freq=38461Hz[+854,-872,+854,-874,+1733,-872,+854,-872,+854,-872,+854,-870,+856,-871,+856,-870,+854,-1721,+854,-872,+1735,-870,+856,-65535,+856,-872,+854,-873,+1732,-873,+854,-870,+854,-872,+854,-872,+854,-872,+855,-872,+854,-1719,+854,-874,+1733,-870,+856,-65535,+854,-874,+852,-875,+1733,-872,+854,-870,+854,-872,+854,-873,+854,-872,+854,-872,+854,-1721,+854,-872,+1733,-872,+854,-65535,+854,-872,+854,-872,+1735,-872,+854,-870,+856,-870,+854,-872,+855,-872,+854,-872,+854,-1721,+854,-872,+1732,-872,+854,-65535][][]

**Comment by bakdamir** [comment]
![image](https://user-images.githubusercontent.com/10049744/68533899-dfc4cf00-0347-11ea-9303-76428d3ea55f.png)
![image](https://user-images.githubusercontent.com/10049744/68533902-f834e980-0347-11ea-8e6c-1f20a47fa030.png)

**Comment by bengtmartensson** [comment]
Working for me

![image](https://user-images.githubusercontent.com/11508922/68534166-6621e680-0331-11ea-976d-5b6fe093eaa6.png)

(It turns on/off a Philips TV :-)).

Make sure you really are using the latest version; then reset properties (File -> Set properties to default; restart).

**Comment by bakdamir** [comment]
Without changes

**Comment by bengtmartensson** [comment]
Try today's ci-build.

**Comment by bengtmartensson** [comment]
Still waiting for feedback.

I cannot reproduce and honestly have no idea what the problem is. Will close shortly unless I get useful feedback.

**Comment by bakdamir** [comment]
Let's close it for now
