### ISSUE TITLE
Wrong export path

### ISSUE THREAD

**Issue by DanielTheGreat** [bengtmartensson/harctoolboxbundle#338]
I entered a path in the 'Export dir.' field, but IRScrutinizer (v2.1.0) totally ignored that path and created the file in the default directory (see screen-shot).
![Wrong_export_path](https://user-images.githubusercontent.com/17305139/69001349-d41d6d80-0930-11ea-8463-0dc23c232a93.png)

**Comment by bengtmartensson** [comment]
You will have to trigger the action of the text file, for example by pressing return, just typing is not enough.

PS. Please use a describing, neutral language and avoid emotionally colored terms. "Totally ignored" implies deliberate evil.

**Comment by DanielTheGreat** [comment]
Sorry about the anthropomorphism!

If this bug (having to hit <Enter> after entering a path) can't be fixed, then please add a warning in the Export pane that this non-standard behaviour is required.
