### ISSUE TITLE
HTTP error 500 when trying to use irdatabase.globalcache.com

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/harctoolboxbundle#34]
When trying to access irdatabase.globalcache.com I get error 500, and "Select%20me%20to%20load" is part of the URL that produces the error. Possibly the URL is not correct?

**Comment by bengtmartensson** [comment]
Cannot reproduce. Works for me. If the problem remains, provide exact instructions on how to reproduce, (Turning on Options -> verbose can be helpful.)

**Comment by probonopd** [comment]
For whatever strange reason it is working today. Closing.
