### ISSUE TITLE
Import from irdb.tk not work

### ISSUE THREAD

**Issue by bdn76** [bengtmartensson/harctoolboxbundle#357]
Import from irdb.tk not work

![20200127130324](https://user-images.githubusercontent.com/17513453/73165776-7f9f2700-4105-11ea-9f9e-b5860a2ab546.png)

**Comment by bengtmartensson** [comment]
irdb.tk is, at least currently, [down](http://www.remotecentral.com/cgi-bin/mboard/rc-custom/thread.cgi?42483). This is not a problem with IrScrutinizer. Therefore closing -- nothing I can do.

Thanx for the report anyhow.
