### ISSUE TITLE
Arduino sketch does not compile on latest Arduino IDE

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/harctoolboxbundle#42]
The Arduino sketch does not compile anymore on the latest (I used hourly) Arduino IDE. For example, it still includes `Platform.h` which was deprecated.
Also it would be nice if the sketch could be directly viewable via git, which means that it should not be put inside a zip.

Edit: just noticed that there is https://github.com/bengtmartensson/AGirs now.

**Comment by bengtmartensson** [comment]
Yeah, it has been replaced by AGirs. "Arduino support" will be replaced by "Girs support" -- see issue #24.

I will probably just remote IrScrutinizer/arduino -- other suggestions? 

Ok to close?

**Comment by probonopd** [comment]
Makes sense to me. Hence closing this.
