### ISSUE TITLE
Arduino sketch could also support WiFi Shields

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/harctoolboxbundle#43]
In addition to Ethernet, the Arduino sketch could also support WiFi Shields.
The required changes seem not so difficult:
https://github.com/sirleech/Webduino/compare/master...acarlton:wifi
It would be nice if they could be wrapped inside `#ifdef` statements similar to https://github.com/rastapasta/strombewusst/blob/master/arduino/arduino.ino.

Edit: just noticed that there is https://github.com/bengtmartensson/AGirs now.

**Comment by bengtmartensson** [comment]
Closing, can continue in AGirs.
