### ISSUE TITLE
Consider using packr for bundling the app

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/harctoolboxbundle#44]
Consider https://github.com/libgdx/packr for generating the Mac(and possibly other OSes) native app.

**Comment by bengtmartensson** [comment]
Thanx for the suggestion.

At least for the time being, I do not consider "native applications" (packages with included JVM) to be a good idea, Instead, I try to provide a _truly portable_ program.

But feel free to do so yourself.

**Comment by probonopd** [comment]
Understand what you are saying. I like your .app though. Feels so much more native on a Mac.

**Comment by bengtmartensson** [comment]
Nice to hear that. BTW, building the Mac app is a PITA, see  http://www.harctoolbox.org/IrScrutinizer.html#Mac+OS+X+app+creation, but since the main problem is the Apple copyright, I do not see a simple solution.

**Comment by probonopd** [comment]
I think there might be ways around that by writing your own app stub or finding a suitable existing one.

**Comment by bengtmartensson** [comment]
This cannot be a new issue, any open source developer for Apple systems must have run into it. Possibly there are already solutions out there? (Apple development forums...)

Personally, it is not on the top of my priorities...

**Comment by probonopd** [comment]
Like [this](https://github.com/tofi86/universalJavaApplicationStub)?

**Comment by probonopd** [comment]
Or even simpler, [this](https://github.com/probonopd/harctoolboxbundle/blob/master/package/IrScrutinizer.app/Contents/MacOS/Launcher)?

**Comment by bengtmartensson** [comment]
Continued as #51.
