### ISSUE TITLE
Use new irdb interface

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/harctoolboxbundle#45]
Using the new [irdb](https://github.com/probonopd/irdb/) interface should make things faster and more robust.

**Comment by bengtmartensson** [comment]
Thank you for informing me. Frankly, _for the time being_, I do not see much use of a migration. The present IrScrutinizer interface is, although not blindingly fast, quite ok. The only use case where the "new one" potentially shines is bulk downloads, a use case that I -- at least presently  -- do not care for.
