### ISSUE TITLE
(GUI) Confirmation exiting dialog if tables non-empty?

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/harctoolboxbundle#86]
Should there be a confirmation dialog before ending the program if, e,g, the tables are non-empty? Or should they quietly be backed up?

Just lost 15 minutes of work... grrr.

**Comment by bengtmartensson** [comment]
There should be an option for this, saved in the properties. Ideally, a "Do not ask again" checkbox.

**Comment by HelenFoster** [comment]
Long-term it would be nice to have "project files", which save the tables and anything else that makes sense. Then, exiting could be the usual "unsaved changes" procedure. I'm thinking of Audacity as an example (work on the project file and export to a standard format when finished).

**Comment by bengtmartensson** [comment]
@HelenFoster : Thanx for the suggestion. Right now, many of the settings, e.g. the parameters on "Generate", are saved between the sessions in the property file. (The number of those parameters may be extended.) You can have several by using the --properties <filename> option, although that is definitely an "expert option".

Also, since IrScrutinizer is not a program that "edits a certain type of file", there is no "save" and "load", but instead a number of import and export functions. 

For this reason, I do not think "project files" fits in, at least not in the current version. Open a separate ticket if appropriate.

**Comment by bengtmartensson** [comment]
Confirmation dialogs with "do not ask again" option implemented.
